spring.application.name=api-versioning-demo
server.port=8080

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# API versioning
api.versioning.default-version=2020-01-01

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
